## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file sage_test.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_0 = Integer(0); _sage_const_1269 = Integer(1269); _sage_const_14 = Integer(14); _sage_const_2 = Integer(2); _sage_const_16 = Integer(16); _sage_const_21 = Integer(21); _sage_const_1 = Integer(1); _sage_const_22 = Integer(22); _sage_const_27 = Integer(27)## This file (sage_test.sagetex.sage) was *autogenerated* from sage_test.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('sage_test', version='2020/08/12 v3.5', version_check=True)
try:
 _st_.current_tex_line = _sage_const_8 
 _st_.inline(_sage_const_0 , latex(number_of_partitions(_sage_const_1269 )))
except:
 _st_.goboom(_sage_const_8 )
_st_.current_tex_line = _sage_const_14 
_st_.blockbegin()
try:
     __tmp__=var("x"); f = symbolic_expression(exp(x) * sin(_sage_const_2 *x)).function(x)
except:
 _st_.goboom(_sage_const_16 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_21 
 _st_.inline(_sage_const_1 , latex(f(x)))
except:
 _st_.goboom(_sage_const_21 )
try:
 _st_.current_tex_line = _sage_const_22 
 _st_.inline(_sage_const_2 , latex(diff(f, x, _sage_const_2 )(x)))
except:
 _st_.goboom(_sage_const_22 )
try:
 _st_.current_tex_line = _sage_const_27 
 _st_.plot(_sage_const_0 , format='notprovided', _p_=plot(f, -_sage_const_1 , _sage_const_1 ))
except:
 _st_.goboom(_sage_const_27 )
_st_.endofdoc()

